### PR TITLE
Feature competing timeout consumers #295 (mongoDB)

### PR DESCRIPTION
**Pull request by CasperTDK**

### CODE REVIEW

**Comment by mookid8000** [comment]
Not sure I follow your code. Before I read it again, I'll briefly explain how the thing with the lease could work.

Due timeouts should be retrieved with a find-and-modify query that queries for

    timeoutIsDue && (leaseHasNotBeenSet || leaseHasExpired)

The `leaseHasNotBeenSet || leaseHasExpired` part can be made easy if the lease defaults to `DateTime.Min`, because then an unset lease and an expired lease will look the same. Thus the query can be reduced to

    timeoutIsDue && leaseHasExpired

which translates to something like the following query and update:

    var now = RebusTimeMachine.Now();
    var criteria = Query.And(Query.LTE(TimeProperty, now), Query.LTE(LeaseProperty, now));

    var leaseExpirationTime = now + TimeSpan.FromMinutes(1);
    var update = Update.Set(LeaseProperty, leaseExpirationTime);
    
As you've figured out, MongoDB's `findAndModify` returns only 1 matching document - therefore, some kind of iteration is necessary, fetching up to e.g. 100 timeouts at a time:

    var dueTimeouts = Enumerable.Range(0, 100)
        .Select(n => GetNextTimeout(criteria, update))
        .TakeWhile(timeout => timeout != null)
        .ToList();

Does it make sense?

**Comment by CasperTDK** [comment]
This is what the code should already do :)

**Comment by mookid8000** [comment]
...but what's the deal with the ultra-short 500 ms lease and the `boundTo` construct?

**Comment by CasperTDK** [comment]
The 500ms is the lease - do you think it will ever take more than 500ms to retrieve and send timeout replies found?
The boundTo ensures that we can iterate 'FindAndModify' and get all documents - and not the same document on every call.

**Comment by mookid8000** [comment]
I'm thinking that retrieving up to 100 timeouts could take a few seconds - the lease must be long enough that even e.g. an Azure-deployed web site in West Europe can pull timeouts from a MongoLab-hosted MongoDB in West US and convert those into timeout replies and delete the timeout documents in time.

Also, the [lease must function as a time-limited lock](http://en.wikipedia.org/wiki/Lease_%28computer_science%29) - which is exactly what it does when you use `findAndModify`: the timeout document will simply not turn up in results until the lease expires....

**Comment by mookid8000** [comment]
PS: I'm not saying that your solution does not work - I'm just hinting at a simpler solution that is easier to understand :)

**Comment by mookid8000** [comment]
Rebus2 has a timeout manager for MongoDB that works with competing consumers

**Pull request closed without merging**
