### PR TITLE
Saga data property names can be specified as strings

### PR DESCRIPTION
**Pull request by seankearon**
Added overloads to allow saga data property names to be specified using strings.

#883

---
Rebus is [MIT-licensed](https://opensource.org/licenses/MIT). The code submitted in this pull request needs to carry the MIT license too. By leaving this text in, __I hereby acknowledge that the code submitted in the pull request has the MIT license and can be merged with the Rebus codebase__.

### CODE REVIEW

**Comment by mookid8000** [comment]
Cool!

One thing though: Would it be possible to copy/paste some or all of the relevant tests and the relevant saga in `TestSagaCorrelation`, so that the new tests will automatically get executed by all implementors as soon as they update their dependency on the contracts NuGet package?

**Comment by seankearon** [comment]
Sure - will look now...

**Comment by seankearon** [comment]
I think I've done that 🤔 : 

I added a [parameter to the base class](https://github.com/seankearon/Rebus/blob/5ac3abb4b4146e6b4fa0c4b637c5a45446f72e5b/Rebus.Tests.Contracts/Sagas/TestSagaCorrelation.cs#L99) to allow the saga to switch from expressions to strings.  

Then I added a new [concrete fixture](https://github.com/seankearon/Rebus/blob/5ac3abb4b4146e6b4fa0c4b637c5a45446f72e5b/Rebus.Tests/Persistence/InMem/TestSagaCorrelationUsingSagaDataPropertyNamesInMem.cs#L7) with the parameter set so that is was called with the string option enabled.  

Should I be calling it differently?

**Comment by mookid8000** [comment]
The problem is that all implementors must *remember* to add a new concrete test fixture to include the new tests.

E.g. Rebus.SqlServer currently has [`TestSagaCorrelationSql`](https://github.com/rebus-org/Rebus.SqlServer/blob/master/Rebus.SqlServer.Tests/Sagas/TestSagaCorrelationSql.cs) .... if it updates its reference to Rebus.Tests.Contracts, then it will not automatically get the new tests.... it will only do that if you add new tests to the `TestSagaCorrelation` class.

**Comment by seankearon** [comment]
Aha! 💡 Thanks, Mogens.  I'll fix that asap.

**Comment by seankearon** [comment]
The tests are now in the `TestSagaCorrelation`! 😺

**Comment by mookid8000** [comment]
Excellent! It's out in Rebus 6.3.0 on NuGet.org now 🙂 

While it's actually strictly speaking a "breaking change" (because the `ICorrelationConfig<>` has had things added to it, and additional implementors are then made incomplete), I chose to only bump minor (6.2.1 👉 6.3.0), because I think it is very uncommon to implement `ICorrelationConfig`.

**Comment by seankearon** [comment]
Fantastic - thanks, Mogens! 🍾

**Pull request merged**
