### PR TITLE
Added support for distributed exclusive saga locks via MySQL tables

### PR DESCRIPTION
**Pull request by kendallb**
This version gets rid of the public .Locking configuration API.

---
Rebus is [MIT-licensed](https://opensource.org/licenses/MIT). The code submitted in this pull request needs to carry the MIT license too. By leaving this text in, __I hereby acknowledge that the code submitted in the pull request has the MIT license and can be merged with the Rebus codebase__.

### CODE REVIEW

**Comment by mookid8000** [comment]
Cool! 🙂 

Since this is a breaking change it'll be  available in Rebus 7.

I've released it as Rebus 7.0.0-b01, which is available on NuGet.org now

**Comment by kendallb** [comment]
Great, thanks! I can update the MySQL tree to build against it now. What would be the ETA for the 7.0.0 release?

**Comment by mookid8000** [comment]
I would like to do a couple of iterations over Rebus' code before releasing a final version 7, so my guess is that it will be out in a couple of weeks

**Comment by kendallb** [comment]
Sounds good to me.

**Pull request merged**
