### PR TITLE
Implemented saga storage logic for RavenDB.

### PR DESCRIPTION
**Pull request by bjomi**
Passes all the BasicLoadAndSaveAndFindOperations tests.

### CODE REVIEW

**Comment by mookid8000** [comment]
excellent work - thanks! :+1: :smiley:

**Comment by mookid8000** [comment]
build server is working - will release it tomorrow in 0.99.22

**Comment by mookid8000** [comment]
It's available in [Rebus.RavenDB](https://www.nuget.org/packages/Rebus.RavenDb/) on NuGet.org now .... thanks for your contribution :)

**Comment by bjomi** [comment]
Great! Thanks.

On Friday, December 18, 2015, Mogens Heller Grabe <notifications@github.com>
wrote:

> It's available in Rebus.RavenDB
> <https://www.nuget.org/packages/Rebus.RavenDb/> on NuGet.org now ....
> thanks for your contribution :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rebus-org/Rebus/pull/381#issuecomment-165700542>.
>


-- 
*Björn Milton*, CEO & Founder

bjorn@roombler.com
Phone: +46 702 35 54 35
Twitter: @bjomi <http://twitter.com/bjomi>
Facebook: facebook.com/roombler

Strandgatan 1
621 57 Visby

**Comment by mclausen** [comment]
This is Awesome! :+1:

**Pull request merged**
