### PR TITLE
#393 feature/non transactional msmq

### PR DESCRIPTION
**Pull request by Martz94**
This is sort of my first time playing with a service bus so just bear with me... :-P

I've tried to follow your check list from [#393](https://github.com/rebus-org/Rebus/issues/393) as closely as possible. There are a few concerns I'm not too sure about though, so I've added comments and `TODO`'s for you to check out. 

Also, 3 tests are failing as they are testing for transactional behaviour (which is gone now when using this new transport)... Didn't know whether to delete the tests or do something else.

Anyway, hope that actually doesn't give you too much work... Happy reviewing!

---
Rebus is [MIT-licensed](https://opensource.org/licenses/MIT). The code submitted in this pull request needs to carry the MIT license too. By leaving this text in, __I hereby acknowledge that the code submitted in the pull request has the MIT license and can be merged with the Rebus codebase__.

### CODE REVIEW

**Comment by mookid8000** [comment]
I haven't had time to look at your PR just yet - sorry about that ... I'll do it, I promise 😄 it'll probably be a few days before I have time though

**Comment by Martz94** [comment]
No worries, take your time.

**Comment by mookid8000** [comment]
Hi @Martz94  -  I am so sorry that I haven't had time to really look at your contribution until now.

As this was a fairly large PR, and due to the fact that the transports are the most central thing in Rebus, I wanted to be pretty thorough when reviewing it.

Looking though your code, I realize that MSMQ unfortunately does not seem to be able to do what is required in order to make this work. Let me explain what this means.... 😒 

You actually kind of hit the nail on the head when you said this:

> 3 tests are failing as they are testing for transactional behaviour (which is gone now when using this new transport)... Didn't know whether to delete the tests or do something else

because _none of the contract tests should be failing_.

The thing is that Rebus makes a promise which it keeps throughout, no matter which transport you choose: It will adhere to a strict [at-least-once delivery guarantee](https://www.google.dk/search?q=at-least-once+delivery).

This means that any errors while handling a received messages should result in the message being put back in the queue... and "any errors" can be anything from a `NullReferenceException` in the handler code to "someone tripped in the power cable and caused everything to blackout".

This should be the case, even with non-transactional MSMQ too - but it seems like it is not possible to achieve, because `messageQueue.Receive(timeout)` does a full receive of the message. There is simply no way to have the message put back in the queue, except, well, actually _manually putting it back in the queue_ (but we would not be around to do that if we suffered a complete, sudden loss of consciousness - with non-transactional MSMQ we would have lost the current message when we woke up).

The way other transports achieve this without the use of "transactions", is by granting a lease on a received message, thus rendering it invisible to other clients. If the receiver then ACKs the message before the lease ends, that means that the message was properly handled. If not, then the message will become visible to other clients again when the lease ends.

The only way to do a transactional receive with MSMQ, it seems, is to create a transactional queue and then supply a `MessageQueueTransaction` to it. But then we're back at the beginning, because we would have to use transactional queues throughout, and that is exactly how the old MSMQ transport works.

I am sorry that it seems like you have done so much work in vain. I really hope you will consider maybe looking at some of the other issues and send another PR 😄

**Comment by Martz94** [comment]
Ok, I see.. Thanks for the detailed explanation!

**Pull request closed without merging**
