### PR TITLE
Added count methods for InMemoryNetwork

### PR DESCRIPTION
**Pull request by CasperTDK**
We have a few small microservices that does not need to be durable. So we just use In Memory transport. However, we do want to query the status of the services and an insight into queue count is helpful.
---
Rebus is [MIT-licensed](https://opensource.org/licenses/MIT). The code submitted in this pull request needs to carry the MIT license too. By leaving this text in, __I hereby acknowledge that the code submitted in the pull request has the MIT license and can be merged with the Rebus codebase__.

### CODE REVIEW

**Comment by mookid8000** [comment]
cool ,thanks 👍

**Comment by CasperTDK** [comment]
@mookid8000  Thanks for the merge. When is a new release planned?

**Comment by mookid8000** [comment]
Before you turn 30!

**Comment by mookid8000** [comment]
(it's out in Rebus 5.0.2, which is on NuGet.org now.... thanks again 👍 )

**Pull request merged**
