### PR TITLE
PR for #448 

### PR DESCRIPTION
**Pull request by Rzpeg**
Fix for issue #448 , includes unit tests
---
Rebus is [MIT-licensed](https://opensource.org/licenses/MIT). The code submitted in this pull request needs to carry the MIT license too. By leaving this text in, __I hereby acknowledge that the code submitted in the pull request has the MIT license and can be merged with the Rebus codebase__.

### CODE REVIEW

**Comment by mookid8000** [comment]
excellent - thanks! 👍

**Comment by mookid8000** [comment]
fixes #448 so I will close that one now

**Comment by mookid8000** [comment]
Quick heads up: You seem to have added FluentAssertions version 4.6.1 _without_ all the binaries 😄 it's not a problem - I fixed it.

I suspect you have a global .gitignore that says to ignore something like `lib/*/*.dll` or something like that..... you probably know it, but it's just something you might want to be aware of... when a repository commits the `packages` folder there will often be lots of stuff that you will then not be adding.

**Comment by Rzpeg** [comment]
Oh, yeah, my fork has all but bins :smile: 
I don't normally commit packages to repo, I use AppVeyor pre-build restore, and yes, I have a few rules in my gitignore :smile:

**Comment by mookid8000** [comment]
I've committed my packages to almost all of my repos since Microsoft went and deleted a package one time 😱 not that I think they would do it again, but I used to be 55% in favor of package restore, now it's the opposite because I like to know that it is slightly more deterministic 😄

**Comment by Rzpeg** [comment]
Well that unfortunate :sweat_smile:

**Pull request merged**
