### PR TITLE
Clean-up solution + Use feature "String Interpolation"

### PR DESCRIPTION
**Pull request by SvenVandenbrande**
---
Rebus is [MIT-licensed](https://opensource.org/licenses/MIT). The code submitted in this pull request needs to carry the MIT license too. By leaving this text in, __I hereby acknowledge that the code submitted in the pull request has the MIT license and can be merged with the Rebus codebase__.

### CODE REVIEW

**Comment by mookid8000** [comment]
wow, you've been busy 😉

**Comment by SvenVandenbrande** [comment]
I have my moments. :)
Sometimes I have a lot of spare time and I do some work. Sometimes 2 or 3 weeks I can't do anything. :)

**Comment by mookid8000** [comment]
cool 👍 thanks for cleaning up the code 😄

**Comment by SvenVandenbrande** [comment]
I hope to do more then only clean up stuff.  :smile:

**Pull request merged**
