### PR TITLE
#1157 add net 6 so dependencies can be decreased

### LINKED ISSUE #1157: Add additional TFM's so package dependencies can be optimised
**Is your feature request related to a problem? Please describe.**
I want to minimise dependencies in my project by utilising framework dependencies wherever possible

**Describe the solution you'd like**
The System.Text.Json & Microsoft.CSharp package becomes conditional so only added for the older frameworks.
Package gain net standard 2.1 & net 5 as TFM

**Describe alternatives you've considered**
Accept the additional dependency

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by thompson-tomo**
---
Rebus is [MIT-licensed](https://opensource.org/licenses/MIT). The code submitted in this pull request needs to carry the MIT license too. By leaving this text in, __I hereby acknowledge that the code submitted in the pull request has the MIT license and can be merged with the Rebus codebase__.

Closes #1157

### CODE REVIEW

**Comment by mookid8000** [comment]
Hi @thompson-tomo , thanks for contributing 🙂 I am not sure I understand what this is about...? I mean, I can see what you changed, but I fail to understand what will be possible that currently isn't....?

**Comment by thompson-tomo** [comment]
The biggest change is the fact the package is now compiled for net 6. The benefit is that release will be smaller as less dependencies & at the same time if a package like STJ was impacted by a CVE the application's using rebus would also be impacted.

**Comment by mookid8000** [comment]
What's STJ and a CVE?

**Comment by thompson-tomo** [comment]
STJ is the system.text.json dependency and a CVE Is a security topic -> https://www.redhat.com/en/topics/security/what-is-cve?darkschemeovr=1

**Comment by mookid8000** [comment]
Ah, I see! I'll merge your PR now then

**Comment by mookid8000** [comment]
It's out as Rebus 8.4.0 on NUGet.org now 🙂  thanks for contributing!

**Comment by thompson-tomo** [comment]
No problem at all. 🙂

**Pull request merged**
