### PR TITLE
Optimize `TransactionContext`

### PR DESCRIPTION
**Pull request by jods4**
`TransactionContext` uses 4 concurrent queues internally. 
Each one is a heavy object, implementation includes at least two arrays of length 32, and around ten fields, in 32 bits we're close to 400 bytes per queue, so 1.5Kb per `TransactionContext`.
Manipulating them is not cheap either.

I replaced them with events (i.e. `MulticastDelegate`), which is `null` if empty, otherwise a linked list of delegates (target + method pointer). Much, much cheaper.

`add` and `remove` on `event` are thread-safe in C#, generated code uses a compare-and-exchange loop. Invoking is also thread safe (based on a snapshot at time of invocation).

**Note that the original code had a race condition** where an action could for example be added to `OnCommitted` and not throw a completed exception, nor be called. 
**I did not fix this race condition and it still exists.**
Easiest fix might be to make all flags volatile and set them before invoking the corresponding event.

I did not bother with emptying the events that will only be called once (i.e. all of them except Commit).

I also extracted the throwing code in `OnXXX` method. It makes those methods very likely to be inlined by JIT.

Finally I removed some async machinery where it was excessive.

---
Rebus is [MIT-licensed](https://opensource.org/licenses/MIT). The code submitted in this pull request needs to carry the MIT license too. By leaving this text in, __I hereby acknowledge that the code submitted in the pull request has the MIT license and can be merged with the Rebus codebase__.

### CODE REVIEW

**Comment by mookid8000** [comment]
This is really good work! 👍 thanks! I'll publish a new prerelease immediately, brb

**Comment by mookid8000** [comment]
Check this out: I just ran the `TestDispatchPerformance` test before and after your optimization.

Here's before:
```
.NET Core 2.1
	Avg s: 3,26354
	Avg msg/s: 30642

	Med s: 3,23851
	Med msg/s: 30878

.NET 4.6
	Avg s: 3,53083
	Avg msg/s: 28322

	Med s: 3,51766
	Med msg/s: 28428

.NET 4.5
	Avg s: 3,70674
	Avg msg/s: 26978

	Med s: 3,49214
	Med msg/s: 28636
```
As you can see, it's right past 30k msg/s on .NET Core and well below on full FX.

Here's AFTER your optimization:
```
.NET Core 2.1
	Avg s: 3,01399
	Avg msg/s: 33179

	Med s: 3,00548
	Med msg/s: 33273

.NET 4.6
	Avg s: 3,34372
	Avg msg/s: 29907

	Med s: 3,35941
	Med msg/s: 29767

.NET 4.5
	Avg s: 3,57061
	Avg msg/s: 28006

	Med s: 3,22244
	Med msg/s: 31032
```
This time it's well past 30k on .NET Core, and almost on 30k with full FX.

With this unscientific benchmark, I think it's safe to say that performance has improved 😎

**Comment by mookid8000** [comment]
it's out in Rebus 6.0.0-b10 on NuGet.org in a few minutes

**Comment by jods4** [comment]
Thanks for benchmarking!

I did this purely on a memory allocation perspective, it's nice to see it actually translates into a real perf improvement. 🎉
Even though it's only a tiny part of sending a message!

**Pull request merged**
