### PR TITLE
Added ASP.NET Core ServiceProvider ContainerAdapter, to integrate Rebus in an ASP.NET Core Web Application built on top of full .NET framework 4.5 and above using the default ServiceContainer

### PR DESCRIPTION
**Pull request by enosrecanati**
---
Rebus is [MIT-licensed](https://opensource.org/licenses/MIT). The code submitted in this pull request needs to carry the MIT license too. By leaving this text in, __I hereby acknowledge that the code submitted in the pull request has the MIT license and can be merged with the Rebus codebase__.

### CODE REVIEW

**Comment by mookid8000** [comment]
Awesome!  😁 

Although I realize now that committing NuGet packages to the code repository will explode completely from now on because the entire .NET framework is downloaded into the packages folder.

Sorry about the hassle – but could you wait until I remove the packages folder from source control and then add your contribution after that?

This way, we can make the entire .NET framework part of Rebus' Git history _by reference_ rather than _by value_ 😀

**Comment by mookid8000** [comment]
I have pushed to master now the removal of the packages folder and a change in .gitignore that starts ignoring them.

Probably the easiest way to go about this would be to simply branch off of my master and copy your additions to that branch, and then PR them to me.

Again: Sorry about the hassle – if it was possible for me to simply accept your PR and clean things up myself I would do it, but I could not do it without leaving the entire .NET framework in Rebus' Git history.

**Comment by enosrecanati** [comment]
I agree, best the way to solve is to ignore the packages folder in the repo and let NuGet to do its work.

No problem, I'll re-branch and submit the changes again :)

**Comment by mookid8000** [comment]
I think you will have to re-branch from my master completely, and then copy your additions into the clone of your fork. 

I think this indicates that what you just did made an even longer Git history: skaermbillede 2016-08-25 kl 09 12 40

**Comment by mookid8000** [comment]
although it may work if you rebase off of my master and squash your commits.... but I'm not enough of a Git wizard to know that

**Comment by enosrecanati** [comment]
Ok, thanks. So we can close this PR and i'll redo the fork.

**Pull request closed without merging**
