### PR TITLE
Fix Sql Server transport and storage lacks SqlConnection costructor #446

### PR DESCRIPTION
**Pull request by zabulus**
---
Rebus is [MIT-licensed](https://opensource.org/licenses/MIT). The code submitted in this pull request needs to carry the MIT license too. By leaving this text in, __I hereby acknowledge that the code submitted in the pull request has the MIT license and can be merged with the Rebus codebase__.

### CODE REVIEW

**Comment by mookid8000** [comment]
I don't mean to be troublesome, but did you consider adding a new implementation of `IDbConnectionProvider`? 

I originally designed it with an interface in place in order to be able to support this exact scenario, so it would be nice if it could make use of that somehow.

**Comment by zabulus** [comment]
Sure no problem.

I have off topic question: why do IDbConnectionProvider and DbConnectionProvider have public visibility? There is no possibility to use user-defined descendants of this classes in rebus.
Do you mind if I change their visibility to internal?

**Comment by mookid8000** [comment]
Are all the SqlServer* persistence implementations internal too?

Sendt fra min iPhone

**Comment by zabulus** [comment]
Nope, all existing implementations have public visibility.

**Comment by mookid8000** [comment]
Ah, good :) the interface should stay public then.... in fact I think that your requirement of supplying the connection from the outside can be implemented without changing anything in the existing implementations, by adding a couple of configuration extensions 

Sendt fra min iPhone

**Comment by zabulus** [comment]
> in fact I think that your requirement of supplying the connection from the outside can be implemented without changing anything in the existing implementations, by adding a couple of configuration extensions

That's exactly what I've added in the PR.

**Comment by mookid8000** [comment]
hmm, I'm looking over your code now... as far as I can tell, the `DbConnectionFactoryProvider` will NOT let you use an already open `SqlConnection` provided from the outside because it will always try to open the connection itself.... I think this pretty much defeats the purpose of being able to supply the connection from the outside in the first place, or is there something I am not getting here?

**Comment by zabulus** [comment]
Indeed.
I can add cheking state of SqlConnection returned from factory method.

**Comment by mookid8000** [comment]
Checking whether the `SqlConnection` was open, and then opening it if necessary, would definitely be one way to do it.

However I'm in doubt as to how useful the `DbConnectionFactoryProvider` would be in its current form. In my opinion it should accept the connection returned by the `Func<SqlConnection>` to be in a usable shape and not do anything to it.

In fact - the more I look at it, the more convinced I am that the `Func` should be `Func<IDbConnection>` because then whoever supplies the `IDbConnection` has more control over what should happen.

For example, `DbConnectionWrapper` can be returned as the `IDbConnection`, which would allow for running both with and without transactions, as well as allowing for managing the connection+transaction externally.

What do you think?

**Comment by zabulus** [comment]
As library user I don't want to be bound to ```IDbConnection```, I have my Sql connection and don't want any additional work to do (inherit from IDbConnection, wrap SqlConnection in it). So I'd like not to change public API side of the PR.

As for your concern for ```DbConnectionFactoryProvider```, I think I can extract all support logic to custom ```IDbConnection``` inheritor, and open connection in it.

**Comment by mookid8000** [comment]
>> As library user I don't want to be bound to IDbConnection, 

You won't. Surely you can base your code on `SqlConnection`, you just pass it to Rebus in something that implements `IDbConnection`.

>> I have my Sql connection and don't want any additional work to do (inherit from IDbConnection, wrap SqlConnection in it). So I'd like not to change public API side of the PR.

Just pass the connection to Rebus using the built-in `DbConnectionWrapper`.

_Additional note:_ if the connection has a started transaction on it, only passing `SqlConnection` won't work because every `connection.CreateCommand()` needs to be followed by a

    command.Transaction = currentSqlTransaction;

and the connection does not provide it anywhere (*). This is what `IDbConnection` should do when you use it to create a command, and it is exactly what `DbConnectionWrapper` does when you initialize it with both a connection and a transaction.


---
(*) This is so stupid that I don't have words for it - why doesn't the connection just set the `Transaction` property to the current `SqlTransaction` automatically when you call `CreateCommand()`?? it doesn't... that's just stupid

**Comment by mookid8000** [comment]
Finally got around to merging this one - sorry about the delay 😁 

Thanks for contributing! 👍

**Comment by mookid8000** [comment]
Will be out in 0.99.66

**Pull request merged**
