### PR TITLE
Assembly auto subscribe

### PR DESCRIPTION
**Pull request by seankearon**
Added the ability to automatically scan assemblies for message handlers and to add corresponding subscriptions.  Looks like this:

    bus.SubscribeByScanningForHandlers(assembly1, assembly2);

### CODE REVIEW

**Comment by mookid8000** [comment]
Right - thanks for your contribution :) but I think this particular feature is better implemented in a separate project so as to avoid needlessly diluting the core APIs.

I've discussed this partciular feature before with @pruiz in #248 where I suggested he put the feature in a `Rebus.Conventions` or `Rebus.AssemblyScanning` project or something like that.

I'll be happy to accept your PR if you do that :) don't worry about writing the .nuspec, I'll make sure that the package gets published with all the other Rebus things.

What do you think?

**Comment by seankearon** [comment]
Sure, makes sense! :)  New update just pushed.  I've created a Rebus.Extensions project and put the `bus.SubscribeByScanningForHandlers(...)` in there as an extension method.  Hope that naming is okay?  

I've left the test in TestRebusBus.cs.  Probably not quite the right place for it as the test exercises an extension, but starting a new fixture felt like littering! :)

Let me know what you think.

**Comment by mookid8000** [comment]
your contribution is available in 0.76.0 which is on NuGet.org shortly - thanks! :+1:

**Comment by seankearon** [comment]
Lovely job, thanks! :)

**Pull request merged**
