### PR TITLE
[WIP] ConcurrentQueue to await non-awaited rebus tasks post handler

### PR DESCRIPTION
**Pull request by colin-higgins**
---

Rebus is [MIT-licensed](https://opensource.org/licenses/MIT). The code submitted in this pull request needs to carry the MIT license too. By leaving this text in, **I hereby acknowledge that the code submitted in the pull request has the MIT license and can be merged with the Rebus codebase**.

@mookid8000 
Thoughts on this kind of approach? 
For https://github.com/rebus-org/Rebus/issues/435

I need to test and whatnot but I figured I'd get your thoughts first. It was the least obtrusive way I could think of.  (Again, haven't tested yet)
Needs some cleanup yet too.

### CODE REVIEW

**Comment by mookid8000** [comment]
Definitely great to see an idea on how it could be done, but as far as I can tell by the work you have done, it would only work with `BuiltinHandlerActivator`... or am I missing something?

You seem to have done one thing though, which I think is pretty brilliant: The `EnqueueTo` extension method, which I think could maybe be changed to something like `EnsureIsAwaited` and look somewhat like this:

	public static EnsureIsAwaited(this Task task) 
	{
		var context = AmbientTransactionContext.Current;
		if (context == null) return; //< we are not in a Rebus handler

		var taskQueue = context.Items.GetOrAdd("tasksToFinish", () => {
			var tasks = new ConcurrentQueue<Task>();
			context.Committed += async () => await Task.WhenAll(tasks);
		});

		taskQueue.Enqueue(task);
	}

(which is written purely from memory – it probably can't compile)

What do you think?

**Comment by mookid8000** [comment]
BTW it looks like you're working on an old fork of Rebus – in case you make another attempt, you should fetch upstream before you start working 😉

**Comment by colin-higgins** [comment]
Yeah it is quite old. I had pulled it down and started scratching around a few months ago. :)

I didn't want to find every point of entry until I vetted the idea.

I very much like your method, I hadn't thought of using the transaction context.
I'll get latest and fork again tonight my time.

**Comment by mookid8000** [comment]
🤘

**Comment by colin-higgins** [comment]
PS, is there ever a situation where there would be no transaction context within a handler?

**Comment by mookid8000** [comment]
> PS, is there ever a situation where there would be no transaction context within a handler (or a future situation)?

No.

> Is it conceivable?

No! 😁   (1)

> And do we really want to wait until it is committed? That sounds too late to me.

I remembered wrong. The API looks like this:

    context.Commit(async () => {
        // async stuff in here
    });

and it is meant for registering actions that must complete BEFORE acknowledging that the message has been properly handled.

IOW it is the right time 😄 

---

1) All good rules have an exception. Since you are asking whether you can ever encounter a situation where there is no transaction context **within a handler**, there is actually one that I can think of: When calling `await Handle(someMessage);` from within a unit test. But the `RebusBus` does not have to account for that in any way.

**Comment by mookid8000** [comment]
Definitely an interesting experiment, but I'm closing this PR for now.

**Pull request closed without merging**
