### PR TITLE
Refactor of activation tests to allow ServiceProvider adapter to be tested

### PR DESCRIPTION
**Pull request by trevorreeves**
I have modified IContainerAdapterFactory to allow for the way in which NetCoreServiceProviderContainerAdapter works in my proposed fix so that ContainerTests & RealContainerTests can be used to test it.

I will submit PRs for the other container repos very soon (probably this afternoon), to make them compatible with this change, but they will need to wait for the new Rebus.Tests.Contracts package to be published I guess?  

---
Rebus is [MIT-licensed](https://opensource.org/licenses/MIT). The code submitted in this pull request needs to carry the MIT license too. By leaving this text in, __I hereby acknowledge that the code submitted in the pull request has the MIT license and can be merged with the Rebus codebase__.

### CODE REVIEW

**Comment by trevorreeves** [comment]
Oh man, so you support quite a few containers :-)  

I've done PRs for ServiceProvider and CastleWindsor.  I'll wait for your feedback on this initial PR first.  I've got a little spare time here and there this week, so can contribute to the rest of changes if appropriate.

Cheers.

**Comment by mookid8000** [comment]
Awesome work! 👏 🎉

**Comment by trevorreeves** [comment]
A little project management on the container repo's that need to be updated:

- ServiceProvider ([PR](https://github.com/rebus-org/Rebus.ServiceProvider/pull/5)) (ready)

- CastleWindsor ([PR](https://github.com/rebus-org/Rebus.CastleWindsor/pull/1#issuecomment-309865521)) (ready)

- AutoFac (to do)

- SimpleInjector (to do)

- Ninject (to do)

- StructureMap (to do)

- LightInject (to do)

**Comment by mookid8000** [comment]
I took the liberty of updating your comment by adding checkboxes.... isn't it neat? 😄

**Pull request merged**
