### PR TITLE
CLS compliance

### LINKED ISSUE #513: CLS compliance
Is there any reason why Rebus assemblies are not marked as CLS compliant?

### PR DESCRIPTION
**Pull request by NKnusperer**
Added CLSCompliant attributes to fix #513

Projects that are now compliant:
Rebus
Rebus.RabbitMq
Rebus.MongoDb
Rebus.AzureServiceBus
Rebus.CastleWindsor
Rebus.Serilog
Rebus.NLog
Rebus.Log4net
Rebus.AmazonSQS
Rebus.Unity
Rebus.Ninject
Rebus.Autofac
Rebus.NewtonsoftJson
Rebus.SimpleInjector
Rebus.XmlConfig
Rebus.StructureMap
Rebus.Forklift.Msmq
Rebus.Forklift.Common
Rebus.Forklift.RabbitMq
Rebus.Forklift.AzureServiceBus
Rebus.Forklift.AzureStorageQueues
Rebus.TransactionScopes
Rebus.Async
Rebus.UnitOfWork
Rebus.Wire
Rebus.Owin
Rebus.Recipes
Rebus.Recipes.Test
Rebus.MsgPack

### CODE REVIEW

**Comment by mookid8000** [comment]
cool! you have made your way through a pretty decent number of files 🏆 😁

**Comment by mookid8000** [comment]
Any reason why e.g. Rebus.AzureStorage, Rebus.DryIoc, Rebus.Jil among others were not marked as CLS compliant?

**Comment by NKnusperer** [comment]
Its mostly because depending third party libraries like `Microsoft.WindowsAzure.Storage.dll` are not.
Once a type from this library is exposed publicly like `CloudStorageAccount` in `AzureStorageQueuesConfigurationExtensions.UseAzureStorageQueues` your own library is also no longer compliant. You can easily check this by yourself, simply set `CLSCompliant` in the `AssemblyInfo` to true, recompile and look at the build output from the compiler. There will be a warning for every violation.

**Comment by mookid8000** [comment]
I see.... initially I thought that you had forgotten to set it to `true` in some of the projects, so I went through and set it for all non-test projects.

I have changed it back again now 😁

**Pull request merged**
